name: Vote Monitor and Onboarding Automation

on:
  issues:
    types: [labeled]

jobs:
  create-onboarding-issue:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'gitvote/passed'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract project name and create onboarding issue
        uses: actions/github-script@v7
        with:
          script: |
            const { createOnboardingIssue, commentAndClose } = require('./scripts/create-onboarding-issue.js');
            
            const issue = context.payload.issue;
            
            console.log('🎉 Vote passed! Creating onboarding issue...');
            console.log('Issue title:', issue.title);
            console.log('Issue number:', issue.number);
            
            // Extract project name from issue title
            const title = issue.title;
            const sandboxMatch = title.match(/^\[Sandbox\]\s*(.+)$/);
            const projectName = sandboxMatch ? sandboxMatch[1].trim() : 'Unknown Project';
            
            console.log('Extracted project name:', projectName);
            
            // Create the onboarding issue
            const onboardingIssueNumber = await createOnboardingIssue(github, context, projectName, issue.number);
            
            // Comment and close the original issue
            await commentAndClose(github, context, issue.number, onboardingIssueNumber, projectName);
            
            console.log(`✅ Successfully created onboarding issue #${onboardingIssueNumber} and closed issue #${issue.number}`);